name: 🚀 Deploy to perfume live
on:
 push:
  branches: main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.signorchoice.com
        username: autodeployer@signorchoice.com
        password: ${{ secrets.PROD_FTP_PASSWORD }}
